<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?= $this->e($title) ?></title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="/style.css">
        <link href="/feed.xml" rel="alternate" type="application/rss+xml">
        <link href="<?= !empty($favicon) ? $favicon : '/favicon.png' ?>" rel="icon">
    </head>
    <body>
        <?php $this->insert('custom::header') ?>
        <div class="container">
            <header class="blog-header py-3">
                <h1 class="blog-title"><a href="/"><?= $title ?></a></h1>
                <?php if (!empty($description)): ?>
                <p class="lead blog-description"><?= $description ?></p>
                <?php endif ?>
            </header>
        </div>
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8 blog-main">
                    <?php foreach ($items as $item): ?>
                    <div class="blog-post">
                        <h2 class="blog-post-title"><a href="<?= $item->get_link() ?>" target="_blank"><?= $item->get_title() ?></a></h2>
                        <p class="blog-post-meta">
                            <?= $item->get_date($date_format) ?>
                            by
                            <a href="<?= $item->get_feed()->get_link() ?>" target="_blank"><?= $item->get_feed()->custom_title ?: $item->get_feed()->get_title() ?></a>
                        </p>
                        <?= tidy_repair_string($item->get_content(), ['show-body-only' => true], 'utf8') ?>
                    </div>
                    <?php endforeach; ?>
                    <nav class="blog-pagination">
                    <?php if ($previous): ?>
                        <a class="btn btn-outline-primary" href="/<?= $previous ?>.html">Previous</a>
                    <?php endif; ?>
                    <?php if ($next): ?>
                        <a class="btn btn-outline-secondary" href="/<?= $next ?>.html">Next</a>
                    <?php endif; ?>
                    </nav>
                </div>
                <aside class="col-md-4 blog-sidebar">
                    <?php if (!empty($about)): ?>
                    <div class="p-3 ml-5 mb-3 bg-light rounded">
                        <h4>About</h4>
                        <p class="mb-0"><?= $about ?></p>
                    </div>
                    <?php endif ?>

                    <div class="p-3 ml-5">
                        <h4>Sources</h4>
                        <ol class="list-unstyled mb-0">
                        <?php foreach ($feeds as $feed): ?>
                            <li><a href="<?= $feed->get_link() ?>" target="_blank"><?= $feed->custom_title ?: $feed->get_title() ?></a></li>
                        <?php endforeach ?>
                        </ol>
                    </div>
                </aside>
            </div>
        </main>
        <footer class="blog-footer">
            <p>Page generated by <a href="http://github.com/blat/potatopotato">potatopotato</a>. Icon by <a href="http://www.flaticon.com/authors/vectors-market">Vectors Market</a>.</p>
            <p>Last update: <?= date($date_format) ?>.</p>
            <p><a href="#">Back to top</a></p>
        </footer>
        <?php if (!empty($piwik)): ?>
        <script type="text/javascript">
        var _paq = _paq || [];
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function(){
            var u="<?= $piwik['url'] ?>";
            _paq.push(["setTrackerUrl", u+"piwik.php"]);
            _paq.push(["setSiteId", <?= $piwik['id'] ?>]);
            var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
            g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
        })();
        </script>
        <noscript><img src="<?= $piwik['url'] ?>piwik.php?idsite=<?= $piwik['id'] ?>" style="border:0;" alt="" /></noscript>
        <?php endif; ?>
    </body>
</html>
